name: Release

on:
  workflow_dispatch:

permissions:
    contents: write
run-name: Release Ubuntu 24.04 LTS (Noble Nombat)

jobs:
  prepare_release:
    name: Create release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2.0.0
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: true
    outputs:
      release_id: ${{ steps.release.outputs.id }}

  build:
    runs-on: ubuntu-latest
    needs: [rootfs, prepare_release]
    name: Build image 

    strategy:
      matrix:
        board:
          - orangepi-5b
          - orangepi-5-pro

        project:
          - preinstalled-desktop
        release:
          - noble

    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Checkout rootfs
        uses: actions/download-artifact@v4.1.2
        with:
	    name: ubuntu-noble-${{ matrix.project }}-arm64-rootfs
	    github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
	    repository: actions/toolkit
	    run-id: 2

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools

      - name: Build
        shell: bash
        run: |
            sudo ./build.sh --board=${{ matrix.board }} --release=${{ matrix.release }} ${{ matrix.project == 'preinstalled-desktop' && '--desktop-only' || matrix.project == 'preinstalled-server' && '--server-only' }}

      - name: Upload
        if: needs.prepare_release.outputs.release_id != '' 
        uses: xresloader/upload-to-github-release@v1
        env:
            GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
          file: images/ubuntu-*-preinstalled-*-arm64-${{ matrix.board }}.*
          draft: true
          overwrite: true

      - name: Clean cache
        shell: bash
        run: sync && sudo rm -rf ./images/ ./build/ && sync
